excluded:
  - Sources/*/*.pb.swift
  - .build
  - Tests/*
  - Package.swift
type_name:
  min_length: 3 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
identifier_name:
  min_length: # only min_length
    error: 3 # only error
  excluded: # excluded via string array
    - id
    - URL
    - fd
    - lh
    - rh
    - i
    - n
    - j
